### ISSUE TITLE
Diferenciar mejor las alternativas y preguntas en la parte visual, ya sean con colores o espaciados.

### ISSUE THREAD

**Issue by AlexanderHuisa** [EnriqueR20/Trivia#1]
Debido a que los colores de las preguntas y las alternativas son lo mismo, a primera impresión no se logra diferenciar entre la pregunta y las alternativas seria bueno que lo dieras un espaciado o cambiar el color ya sea de la pregunta o de las alternativas.

![image](https://user-images.githubusercontent.com/68964232/190284449-f470efb1-e9a0-4421-becc-b1fa645035c2.png)

**Comment by EnriqueR20** [comment]
Se realizo el espaciado de la pregunra y diferencia de colores de las alternativas.
![color](https://user-images.githubusercontent.com/113269346/190286885-316696d2-a615-4dde-8825-775ad849d1fe.png)
