### ISSUE TITLE
Llevar un estándar de colores para el informe de puntos.

### ISSUE THREAD

**Issue by AlexanderHuisa** [EnriqueR20/Trivia#2]
La funcionalidad de la trivia esta muy bien realizada pero, al momento de  mostrarme la cantidad de puntos que llevo hasta el momento unas me muestra de color rojo y en otras de color blanco, seria bueno que estandarice dicha seccion.

![image](https://user-images.githubusercontent.com/68964232/190286342-9b5fe551-fd70-4271-91bc-b02e96d381bb.png)

**Comment by EnriqueR20** [comment]
Se uniformo el color del puntaje acumulado
![rojo](https://user-images.githubusercontent.com/113269346/190287454-5f153577-462f-4a06-8f40-b79ad1b158d8.png)
