### ISSUE TITLE
Sigue pidiendo nombre  nombre en el segundo intento.

### ISSUE THREAD

**Issue by AlexanderHuisa** [EnriqueR20/Trivia#3]
Al momento de realizar mi segundo intento, me pide mi nombre de nuevo, seria bueno que me pida solo al inicio.

![image](https://user-images.githubusercontent.com/68964232/190287943-b2b61cf1-2720-4bbb-aafd-f45fd20ab3c4.png)

**Comment by EnriqueR20** [comment]
Se soluciono el error y ya no pedirá el nombre cuando quiera repetir la trivia
![2intento](https://user-images.githubusercontent.com/113269346/190290167-fae418e8-68dd-4866-bbc9-d46477c751c0.png)
